openapi: 3.0.0
info:
  title: Game Coordinator API
  version: 1.0.0
paths:
  /games:
    post:
      summary: Create a game
      responses:
        '200':
          description: Game created
  /routing/{gameId}:
    get:
      summary: Get routing information for a game
      parameters:
        - in: path
          name: gameId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Routing info
