openapi: 3.0.0
info:
  title: Clubs Service API
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
  /clubs:
    post:
      summary: Create a club
      responses:
        '200':
          description: Club created
  /clubs/{id}/join:
    post:
      summary: Join a club
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Joined club
  /clubs/{id}:
    get:
      summary: Get club information
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Club data
