version: '3.8'

services:
  auth-service:
    volumes:
      # Mount source code for development
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    command: npm run dev