openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
  /auth/register:
    post:
      summary: Register a new user
      responses:
        '200':
          description: Registered
  /auth/login:
    post:
      summary: User login
      responses:
        '200':
          description: Logged in
  /auth/password-reset/request:
    post:
      summary: Request password reset
      responses:
        '200':
          description: Reset requested
  /auth/password-reset/confirm:
    post:
      summary: Confirm password reset
      responses:
        '200':
          description: Password reset
  /auth/logout:
    post:
      summary: Logout current user
      responses:
        '200':
          description: Logged out
  /auth/me:
    get:
      summary: Get current user profile
      responses:
        '200':
          description: Profile data
  /auth/refresh:
    post:
      summary: Refresh authentication token
      responses:
        '200':
          description: Token refreshed
  /auth/verify-email:
    post:
      summary: Verify email address
      responses:
        '200':
          description: Email verified
  /auth/change-password:
    post:
      summary: Change user password
      responses:
        '200':
          description: Password changed
